
### We are going to learn about Pandas and Numpy from very basic to as deep as possible 

--- to use any library first step what we have to do is tell python to use this library or module by importing it 

In [2]:
import pandas as pd
import numpy as np

# Numpy

--- Create 1d array

In [4]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

--- Create 2d array

In [5]:
arr2 = np.array([[1,2,3],[4,6,7]])
arr2

array([[1, 2, 3],
       [4, 6, 7]])

In [18]:


# -----  type() function is used to know the datatype of data 
print("type----",type(arr1),end="\n\n")


### what ravel does is it basically convert any dimemsion array into One dimension
new  = np.ravel(arr2)
print("ravel ---",new,end="\n\n\n")



## create array of zero's by providing dimension

zero1d = np.zeros((1,5))
zero2d = np.zeros((2,2))

print("Zeros 1dimesion---\n",zero1d,end="\n\n\n")
print("Zeros 2dimesion---\n",zero2d,end="\n\n\n")



## linspace is used to 
new = np.linspace(1,20,5)
print("Linspace ----",new,end="\n\n\n")


## convert list to np array
new = list([5,4,6,9])
new = np.array(new)


print("Before reshape",new)

## convert any array according to required shape by using reshape() method
new = new.reshape(2,2)
print("Reshape----\n",new,end="\n\n\n")

new = np.zeros(8)
new = new.reshape(2,2,2)
print("3d Array----\n",new,"\n")


new1  = np.array([1,2,3,4,5,6,7,8,9])


new = slice(1,10,2)

new = new1[new]
print("Slicing ---\n",new)



###random value which gives with gaussian equ

np.random.rand(400,8)

type---- <class 'numpy.ndarray'>

ravel --- [1 2 3 4 6 7]


Zeros 1dimesion---
 [[0. 0. 0. 0. 0.]]


Zeros 2dimesion---
 [[0. 0.]
 [0. 0.]]


Linspace ---- [ 1.    5.75 10.5  15.25 20.  ]


Before reshape [5 4 6 9]
Reshape----
 [[5 4]
 [6 9]]


3d Array----
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]] 

Slicing ---
 [2 4 6 8]


array([[0.13436627, 0.67527466, 0.76667707, ..., 0.448632  , 0.82956849,
        0.16700862],
       [0.84982554, 0.60821914, 0.50295731, ..., 0.11696949, 0.16155854,
        0.44110793],
       [0.87274336, 0.47565133, 0.43342879, ..., 0.181846  , 0.97414112,
        0.83353932],
       ...,
       [0.33156907, 0.65052044, 0.09662626, ..., 0.32565759, 0.10965606,
        0.47787467],
       [0.19134187, 0.8267348 , 0.2998062 , ..., 0.29162653, 0.48507097,
        0.25790005],
       [0.40915989, 0.87854727, 0.85836177, ..., 0.55339738, 0.31152732,
        0.2857555 ]])

### More with numpy

In [23]:
# get single dimension array using arrange function just provide range
ra = np.arange(10)
ra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# know the shape of matrix  (rows,clumns)
a = np.array([[0,1],
             [1,2],
             [4,5]])
a.shape

(3, 2)

In [20]:
## assign float range from 0 to <7
b = np.arange(7, dtype='f')
b

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [21]:
##  assign complex value 
b = np.arange(7, dtype='D')
b

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

## One-dimensional slicing and indexing

In [22]:
a = np.arange(9)
a[3:7]

array([3, 4, 5, 6])

In [26]:
## We can choose elements from indexes 0 to 7 and by increment of 2:
a[:7:2]

array([0, 2, 4, 6])

In [27]:
## Just as normal python code  we also can use negative indices and reverse the array:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
## now let's try above learnt concept

##  crete matrix of 2 x 3

x = np.array([[2,3,4], [5,6,7]])   

print(x.shape,"shape ")
print(x)
print()
# now reshape into 3 x 2 matrix
x = np.reshape(x, (3, 2))
print(x)

(2, 3) shape 
[[2 3 4]
 [5 6 7]]

[[2 3]
 [4 5]
 [6 7]]


In [43]:
# transpose of matrix
x = np.array([[1,2,3],
            [4,5,6],
             [7,8,9],
             [10,11,12]])
print("before transpose\n",x)
np.transpose(x)

before transpose
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [51]:
# flatten will convert and return single dimensional array 
# it contain 4 order   C   A   F  K   (Note : try to search all order of flatten on Internet)
a = np.array([[1,2,3],[4,5,6]])

b =np.array([[1,2,3],
            [4,5,6],
             [7,8,9],
             [10,11,12]])
print(a.flatten(order= 'A'))

# order F choose elemnt column wise 
print(b.flatten(order = "F"))


[1 2 3 4 5 6]
[ 1  4  7 10  2  5  8 11  3  6  9 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [52]:
# ravel is also used to convert the entire matrix into single dimension array


b =np.array([[1,2,3],
            [4,5,6],
             [7,8,9],
             [10,11,12]])

np.ravel(b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
# we can convert array into matrix using np.mat
b =np.array([[1,2,3],
            [4,5,6],
             [7,8,9],
             [10,11,12]])

print("Before convert ",type(b))
c = np.mat(b)
print("After convert",type(c))

Before convert  <class 'numpy.ndarray'>
After convert <class 'numpy.matrix'>


In [61]:
#We can also invert the entire matrix using invert function in numpy

c = np.mat(np.array([[1,2,3],
            [4,5,6],
             [7,8,9],
             [10,11,12]]))
print("Before Invert\n",c)

d = np.invert(c)
print("After invert\n", d)

Before Invert
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
After invert
 [[ -2  -3  -4]
 [ -5  -6  -7]
 [ -8  -9 -10]
 [-11 -12 -13]]


# Pandas

Now before going to use the very first function of pandas i would strongly suggest you to check out what is pandas.

   * Slicing the DataFrame
   * Joining and Merging
   * Changing the Index
   * Concatenation
   * Data conversion
   * Changing the Headers

In [62]:
# import library

import pandas as pd

## Series

In [69]:
np.arange(0,20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [91]:
# series is 1 dimesional datastructure in pandas 

list1 = [1,2,3,4,5,5]

ser1 = pd.Series(list1,index=np.arange(1,7))
print(ser1)

1    1
2    2
3    3
4    4
5    5
6    5
dtype: int64


In [92]:
# How to get element from the pandas series 

#by providing index
print("Single element",ser1[1],"\n")

#by providing range of index
print("Multiple element\n",ser1[2:5])


Single element 1 

Multiple element
 3    3
4    4
5    5
dtype: int64


In [99]:
# find max ,min from the series

##  Mathematical function which you can apply on pandas series 

print("Max", ser1.max())
print("Min", ser1.max())
print("Mean", ser1.mean())
print("Mode", ser1.mode())
print("Median", ser1.median())



Max 5
Min 5
Mean 3.3333333333333335
Mode 0    5
dtype: int64
Median 3.5


In [112]:
# ---- some attrinutes which we can apply on pandas series

# fetch the element by position

print("iat",ser1.iat[2])

# use iloc which is purely integer based indexing for selection by postion
print("\n iloc \n",ser1.iloc[1:4])

#shape
print("\n shape \n",ser1.shape)

iat 3

 iloc 
 2    2
3    3
4    4
dtype: int64

 shape 
 (6,)


In [115]:
## append 2 sereies

l1 = ['a','b','c','d','e']
l2 = [1,2,3,4,5]

s1 = pd.Series(l1)
s2 = pd.Series(l2)

s1.append(s2)

0    a
1    b
2    c
3    d
4    e
0    1
1    2
2    3
3    4
4    5
dtype: object

# Pandas DataFrame

## Dataframe is 2d datastructure in pandas

we can create dataframe from list, dictionary and from any imported data like .csv , .json  and even you can directly use data from your database and can convert into Dataframe

In [121]:
# list  ---> Data Frame

l1 = list([[1,2,3,4,5],['a','b','c','d','e']])

df = pd.DataFrame(np.transpose(l1))
df

0  1
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e

In [125]:
## pass list with index the size of column in data and the index you provide must be same
l1 = list([[1,2,3,4,5],['a','b','c','d','e']])

df = pd.DataFrame(np.transpose(l1), index = [10,20,30,40,50])
df

0  1
10  1  a
20  2  b
30  3  c
40  4  d
50  5  e

In [136]:
# you can also set index by chossing any column in dataset

l1 = list([[1,2,3,4,5],['a','b','c','d','e']])

df = pd.DataFrame(np.transpose(l1))
print("Before Indexing ---\n", df)


#provide index
df.set_index(1)

Before Indexing ---
    0  1
0  1  a
1  2  b
2  3  c
3  4  d
4  5  e


0
1   
a  1
b  2
c  3
d  4
e  5

In [139]:
## dictonary ----> dataframe


dic1 = {"Name":["John","Messi","Tom","SRK"],
        "Age":[40,32,45,46],
       "City":["US","Argentina","US","India"]}

df = pd.DataFrame(dic1)
df

Name  Age       City
0   John   40         US
1  Messi   32  Argentina
2    Tom   45         US
3    SRK   46      India

In [156]:
## now before going to deal with real Dataset let's before learn some attributes and function which is very usefull

# we can know all attributes names from the dataset
print("Columns:",df.columns)

# get shape of dataset
print("\nShape:",df.shape)

#get single columns from the dataset by using 
print("\nColumn 1 :\n",df["Name"])

# select Multiple columns 
print("\nColumn 2,3 :\n",df[df.columns[1:3]])

Columns: Index(['Name', 'Age', 'City'], dtype='object')

Shape: (4, 3)

Column 1 :
 0     John
1    Messi
2      Tom
3      SRK
Name: Name, dtype: object

Column 2,3 :
    Age       City
0   40         US
1   32  Argentina
2   45         US
3   46      India


####  fetch columns with different methods iloc, loc, ix

 * loc gets rows (or columns) with particular labels from the index.
 * iloc gets rows (or columns) at particular positions in the index (so it only takes integers).
 * ix usually tries to behave like loc but falls back to behaving like iloc if a label is not present in the index.

In [177]:
# fetch the row which has index no as 3

print("row 3 :\n",df.loc[3])

# fetch the row 2:3
print("\n\n row 2 , 3 :\n",df.iloc[1:3])


# we can also select columumns with rows select only name and age of TOM 
print("\n\n row and colum : \n",df.iloc[2,1:3])



# check datatype 
print("\nDatatype : ",df.dtypes)


row 3 :
 Name      SRK
Age        46
City    India
Name: 3, dtype: object


 row 2 , 3 :
     Name  Age       City
1  Messi   32  Argentina
2    Tom   45         US


 row and colum : 
 Age     45
City    US
Name: 2, dtype: object

Datatype :  Name    object
Age      int64
City    object
dtype: object


## Merging in Pandas

In [197]:
## to merge dataframe we have to pass the parameter that how we want to merge , on which column we 
# want to merge 
# in merge the one attribute has to be same in both dataframes

df1 = {"Name":["John","Messi","Tom","SRK","Rock","Vin Diesel"],
        "Age":[40,32,45,46,45,40],
       "City":["US","Argentina","US","India","US","UK"]}

df2 = {"Name":["John","Messi","Tom","SRK","Ronaldo"],
        "Profession":["wrestling","Athelte","Actor","Actor","Athlete"]}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)

#Inner merge
print(" Inner Merge:  \n",df1.merge(df2,on='Name',how='inner'))

 
#Outer merge
print(" \n\nRight Merge:  \n",df1.merge(df2,on='Name',how='right'))

#Left merge
print(" \n\nLeft Merge:  \n",df1.merge(df2,on='Name',how='left'))


#outer join
print(" \n\nOuter Merge:  \n",df1.merge(df2,on='Name',how='outer'))



 Inner Merge:  
     Name  Age       City Profession
0   John   40         US  wrestling
1  Messi   32  Argentina    Athelte
2    Tom   45         US      Actor
3    SRK   46      India      Actor
 

Right Merge:  
       Name   Age       City Profession
0     John  40.0         US  wrestling
1    Messi  32.0  Argentina    Athelte
2      Tom  45.0         US      Actor
3      SRK  46.0      India      Actor
4  Ronaldo   NaN        NaN    Athlete
 

Left Merge:  
          Name  Age       City Profession
0        John   40         US  wrestling
1       Messi   32  Argentina    Athelte
2         Tom   45         US      Actor
3         SRK   46      India      Actor
4        Rock   45         US        NaN
5  Vin Diesel   40         UK        NaN
 

Outer Merge:  
          Name   Age       City Profession
0        John  40.0         US  wrestling
1       Messi  32.0  Argentina    Athelte
2         Tom  45.0         US      Actor
3         SRK  46.0      India      Actor
4        Rock  4

## Join operation in Pandas

In [221]:
## Join is same work as merge bit the difference is that it join the datframe
# on the base of commmon index name

# * Both dataframe must have different attributes names

df1 = {"Name":["John","Messi","Tom"],
        "Age":[40,32,45],
       "City":["US","Argentina","US"]}

df2 = {"Names":["John","Messi","Tom","SRK"],
        "Profession":["wrestling","Athelte","Actor","Actor"]}

df1 = pd.DataFrame(df1, index = ['I1','I2','I3'])
df2 = pd.DataFrame(df2, index = ['I1','I2','I3','I8'])

#inner join
print("Inner join\n",df1.join(df2,how="inner"))

#outer join
print("\n\nOuter join\n",df1.join(df2,how="outer"))

#left join
print("\n\nLeft join\n",df1.join(df2,how="left"))

#right join
print("\n\n Right join\n",df1.join(df2,how="right"))

Inner join
      Name  Age       City  Names Profession
I1   John   40         US   John  wrestling
I2  Messi   32  Argentina  Messi    Athelte
I3    Tom   45         US    Tom      Actor


Outer join
      Name   Age       City  Names Profession
I1   John  40.0         US   John  wrestling
I2  Messi  32.0  Argentina  Messi    Athelte
I3    Tom  45.0         US    Tom      Actor
I8    NaN   NaN        NaN    SRK      Actor


Left join
      Name  Age       City  Names Profession
I1   John   40         US   John  wrestling
I2  Messi   32  Argentina  Messi    Athelte
I3    Tom   45         US    Tom      Actor


 Right join
      Name   Age       City  Names Profession
I1   John  40.0         US   John  wrestling
I2  Messi  32.0  Argentina  Messi    Athelte
I3    Tom  45.0         US    Tom      Actor
I8    NaN   NaN        NaN    SRK      Actor


## concenation in pandas

In [228]:
# Concatenat the dataframe

df1 = {"Name":["John","Messi","Tom","SRK","Rock","Vin Diesel"],
        "Age":[40,32,45,46,45,40],
       "City":["US","Argentina","US","India","US","UK"]}

df2 = {"Name":["John","Messi","Tom","SRK","Ronaldo"],
        "Profession":["wrestling","Athelte","Actor","Actor","Athlete"]}

df1 = pd.DataFrame(df1)
df2 = pd.DataFrame(df2)

pd.concat([df1,df2])

Name   Age       City Profession
0        John  40.0         US        NaN
1       Messi  32.0  Argentina        NaN
2         Tom  45.0         US        NaN
3         SRK  46.0      India        NaN
4        Rock  45.0         US        NaN
5  Vin Diesel  40.0         UK        NaN
0        John   NaN        NaN  wrestling
1       Messi   NaN        NaN    Athelte
2         Tom   NaN        NaN      Actor
3         SRK   NaN        NaN      Actor
4     Ronaldo   NaN        NaN    Athlete

## Importing different type of data using Pandas

### by using pandas you can able to import any type of data using [pandas.read_] function data like csv, json xls,etc 

In [ ]:
#all you need is location of data

data= pd.read_csv("location")
pd.read
df = pd.DataFrame(data)

##similarly you can use read_json, read_excel, read_clipbord, etc

## Save Data using Pandas

In [231]:
# same as reading data you can save you dataframe in anyformat

dataframe.to_csv('C:\Users\Faiz\Downloads\a.csv')

##similarly you can use to_json, to_excel, to_sql, etc

## Let's work on real data 

In [232]:
# load the data
data = pd.read_csv("C:/Users/Faiz/Downloads/mtcars.csv")


In [233]:
# see the top and bottom data using head() and tail() fnction

print("Head\n",data.head())
print("\nTail\n",data.tail())

Head
                model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  

Tail
              model   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2

In [234]:
# fetch the attributes
data.columns

Index(['model', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [235]:
#fetch the shape  (rows,columns)
data.shape

(32, 12)

In [236]:
# fetch the description of data using describe()

data.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [237]:
# get the information of data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [248]:
#now lets apply mathematical functions on mpg() variable

mpg = data["mpg"]

print("Mean is ",mpg.mean(),end="\n")

print("Median is",mpg.median(),end="\n")

print("mode is",mpg.mode(),end="\n")

print("Std is", mpg.std(),end="\n")

print("Variance",mpg.var(),end="\n")

print("Maximum",mpg.max(),end="\n")

print("Minimum",mpg.min(),end="\n")

print("Sum of entire column",mpg.sum(),end="\n")

Mean is  20.090624999999996
Median is 19.2
mode is 0    10.4
1    15.2
2    19.2
3    21.0
4    21.4
5    22.8
6    30.4
dtype: float64
Std is 6.026948052089105
Variance 36.32410282258065
Maximum 33.9
Minimum 10.4
Sum of entire column 642.9000000000001


In [242]:
# check is there is null value available
data.isnull()

model    mpg    cyl   disp     hp   drat     wt   qsec     vs     am  \
0   False  False  False  False  False  False  False  False  False  False   
1   False  False  False  False  False  False  False  False  False  False   
2   False  False  False  False  False  False  False  False  False  False   
3   False  False  False  False  False  False  False  False  False  False   
4   False  False  False  False  False  False  False  False  False  False   
5   False  False  False  False  False  False  False  False  False  False   
6   False  False  False  False  False  False  False  False  False  False   
7   False  False  False  False  False  False  False  False  False  False   
8   False  False  False  False  False  False  False  False  False  False   
9   False  False  False  False  False  False  False  False  False  False   
10  False  False  False  False  False  False  False  False  False  False   
11  False  False  False  False  False  False  False  False  False  False   
12  False  False  False  False  False  False  False  False  False  False   
13  False  False  False  False  False  False  False  False  False  False   
14  False  False  False  False  False  False  False  False  False  False   
15  False  False  False  False  False  False  False  False  False  False   
16  False  False  False  False  False  False  False  False  False  False   
17  False  False  False  False  False  False  False  False  False  False   
18  False  False  False  False  False  False  False  False  False  False   
19  False  False  False  False  False  False  False  False  False  False   
20  False  False  False  False  False  False  False  False  False  False   
21  False  False  False  False  False  False  False  False  False  False   
22  False  False  False  False  False  False  False  False  False  False   
23  False  False  False  False  False  False  False  False  False  False   
24  False  False  False  False  False  False  False  False  False  False   
25  False  False  False  False  False  False  False  False  False  False   
26  False  False  False  False  False  False  False  False  False  False   
27  False  False  False  False  False  False  False  False  False  False   
28  False  False  False  False  False  False  False  False  False  False   
29  False  False  False  False  False  False  False  False  False  False   
30  False  False  False  False  False  False  False  False  False  False   
31  False  False  False  False  False  False  False  False  False  False   

     gear   carb  
0   False  False  
1   False  False  
2   False  False  
3   False  False  
4   False  False  
5   False  False  
6   False  False  
7   False  False  
8   False  False  
9   False  False  
10  False  False  
11  False  False  
12  False  False  
13  False  False  
14  False  False  
15  False  False  
16  False  False  
17  False  False  
18  False  False  
19  False  False  
20  False  False  
21  False  False  
22  False  False  
23  False  False  
24  False  False  
25  False  False  
26  False  False  
27  False  False  
28  False  False  
29  False  False  
30  False  False  
31  False  False

In [246]:
# use sum value to see any null value availabe
data.isnull().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [249]:
# fetch column using number

data[data.columns[2:5]]

cyl   disp   hp
0     6  160.0  110
1     6  160.0  110
2     4  108.0   93
3     6  258.0  110
4     8  360.0  175
5     6  225.0  105
6     8  360.0  245
7     4  146.7   62
8     4  140.8   95
9     6  167.6  123
10    6  167.6  123
11    8  275.8  180
12    8  275.8  180
13    8  275.8  180
14    8  472.0  205
15    8  460.0  215
16    8  440.0  230
17    4   78.7   66
18    4   75.7   52
19    4   71.1   65
20    4  120.1   97
21    8  318.0  150
22    8  304.0  150
23    8  350.0  245
24    8  400.0  175
25    4   79.0   66
26    4  120.3   91
27    4   95.1  113
28    8  351.0  264
29    6  145.0  175
30    8  301.0  335
31    4  121.0  109

In [253]:
# fetch rowns using iloc and loc

data.loc[0:25,:]

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1   
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1   
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1   
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0   
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0   
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0   
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0   
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0   
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0   
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0   
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0   
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0   
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0   
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0   
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0   
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0   
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0   
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1   
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1   
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1   
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0   
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0   
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0   
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0   
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0   
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1   

    gear  carb  
0      4     4  
1      4     4  
2      4     1  
3      3     1  
4      3     2  
5      3     1  
6      3     4  
7      4     2  
8      4     2  
9      4     4  
10     4     4  
11     3     3  
12     3     3  
13     3     3  
14     3     4  
15     3     4  
16     3     4  
17     4     1  
18     4     2  
19     4     1  
20     3     1  
21     3     2  
22     3     2  
23     3     4  
24     3     2  
25     4     1

In [255]:
# find correlation on data
data.corr()

mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000